version: '3.8'

networks:
  demo_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:/ProgramData/MySQL/data
  mysql_conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:/ProgramData/MySQL/conf
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:/ProgramData/Redis/data

services:
  mysql:
    image: mysql:8.0
    container_name: demo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mq@31072001
      MYSQL_DATABASE: demo
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3306:3306"
    volumes:
      # Dữ liệu DB thực sẽ nằm ở thư mục local này
      - mysql_data:/var/lib/mysql
      - mysql_conf:/etc/mysql/conf.d
    networks:
      - demo_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-p12345678" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: demo_mysql_admin
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: nette
    networks:
      - demo_network
    depends_on:
      mysql:
        condition: service_healthy

  redis:
    image: redis:7.2-alpine
    container_name: demo_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - demo_network
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "mq@31072001"]

  redisinsight:
    image: redis/redisinsight:latest
    container_name: demo_redis_insight
    restart: always
    ports:
      - "8001:5540"
    networks:
      - demo_network

